# Generated by Django 6.0.2 on 2026-02-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
