# Generated by Django 6.0.2 on 2026-02-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        ('tenants', '0002_tenant_house_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='house_number',
        ),
        migrations.AddField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='houses.property'),
        ),
    ]
