# Generated by Django 6.0.2 on 2026-02-16 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_tenant_house_number_tenant_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='rent_due_day',
            field=models.IntegerField(default=1, help_text='Day of the month when rent is due (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
