micronaut:
  application:
    name: rent-management
  server:
    port: 8000
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - http://localhost:5173
            - http://192.168.100.242
          allowed-methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
  views:
    thymeleaf:
      enabled: true

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/rent_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages:
        - com.rentmanagement.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: com.rentmanagement.config.DjangoNamingStrategy

jackson:
  property-naming-strategy: SNAKE_CASE
  serialization:
    write-dates-as-timestamps: false

netty:
  default:
    allocator:
      max-order: 3

logger:
  levels:
    com.rentmanagement: DEBUG
    io.micronaut.data: DEBUG
