# Generated by Django 6.0.2 on 2026-02-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('LATE', 'Late'), ('FAILED', 'Failed'), ('SEVERE', 'Severe'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20),
        ),
    ]
