# Generated by Django 6.0.2 on 2026-02-20 07:50

from django.db import migrations, models


def backfill_payment_amounts(apps, schema_editor):
    """
    Backfill original_amount and amount_paid for existing payment records.
    - original_amount = amount (preserve the billing amount)
    - For PAID payments: amount_paid = amount (fully paid)
    - For unpaid payments: amount_paid = 0
    """
    Payment = apps.get_model('payments', 'Payment')

    # Set original_amount = amount for all records
    Payment.objects.all().update(original_amount=models.F('amount'))

    # Set amount_paid = amount for all PAID records
    Payment.objects.filter(status='PAID').update(amount_paid=models.F('amount'))


def reverse_backfill(apps, schema_editor):
    """Reverse: reset amount_paid and original_amount to 0."""
    Payment = apps.get_model('payments', 'Payment')
    Payment.objects.all().update(amount_paid=0, original_amount=0)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_payment_fields'),
    ]

    operations = [
        migrations.RunPython(backfill_payment_amounts, reverse_backfill),
    ]
