# Generated by Django 6.0.2 on 2026-02-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_backfill_payment_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='utilization_data',
            field=models.JSONField(blank=True, default=list, help_text='JSON breakdown of how this payment was allocated'),
        ),
    ]
