# Generated by Django 6.0.2 on 2026-02-20 02:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('id_number', models.CharField(blank=True, help_text='National ID or tax ID', max_length=50)),
                ('kra_pin', models.CharField(blank=True, help_text='KRA PIN for tax purposes', max_length=20)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=15)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Monthly base salary', max_digits=12)),
                ('pay_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('nhif_number', models.CharField(blank=True, help_text='NHIF membership number', max_length=30)),
                ('nssf_number', models.CharField(blank=True, help_text='NSSF membership number', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'February 2026 Payroll'", max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_date', models.DateField(help_text='Date employees are paid')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_employer_taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paye_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pay As You Earn tax', max_digits=12)),
                ('nhif_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='NHIF employee contribution', max_digits=12)),
                ('nssf_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='NSSF employee contribution', max_digits=12)),
                ('housing_levy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Housing levy deduction', max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deduction_notes', models.CharField(blank=True, max_length=500)),
                ('employer_nhif', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('employer_nssf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_direct_deposit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paychecks', to='payroll.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paychecks', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['employee__last_name'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
