# Generated by Django 6.0.2 on 2026-02-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='house_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('house_number', 'address')},
        ),
    ]
